// Auto-generated 120-Player Interstellar Roster
export const GALACTIC_ROSTER = [
  {
    "id": "bb_1",
    "name": "Isaiah Anderson",
    "team": "Brooklyn Biotics",
    "teamColor": "#00c8ff",
    "position": "Cyborg Pitcher",
    "jersey_number": 53,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "bb_2",
    "name": "Elijah Wilson",
    "team": "Brooklyn Biotics",
    "teamColor": "#00c8ff",
    "position": "Bionic Shortstop",
    "jersey_number": 76,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "bb_3",
    "name": "Unit 91-E",
    "team": "Brooklyn Biotics",
    "teamColor": "#00c8ff",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 17,
    "gender": "male",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "bb_4",
    "name": "James Williams",
    "team": "Brooklyn Biotics",
    "teamColor": "#00c8ff",
    "position": "Laser Outfielder",
    "jersey_number": 57,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "bb_5",
    "name": "Vor Void",
    "team": "Brooklyn Biotics",
    "teamColor": "#00c8ff",
    "position": "Utility Android",
    "jersey_number": 90,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "bb_6",
    "name": "Unit 58-E",
    "team": "Brooklyn Biotics",
    "teamColor": "#00c8ff",
    "position": "Hover-Base Stealer",
    "jersey_number": 14,
    "gender": "male",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "bb_7",
    "name": "Valentina Perez",
    "team": "Brooklyn Biotics",
    "teamColor": "#00c8ff",
    "position": "Plasma Catcher",
    "jersey_number": 34,
    "gender": "female",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "bb_8",
    "name": "Daiki Kato",
    "team": "Brooklyn Biotics",
    "teamColor": "#00c8ff",
    "position": "Relief Pitcher",
    "jersey_number": 13,
    "gender": "male",
    "home_planet": "Proxima Centauri b",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "bb_9",
    "name": "Grox Alpha",
    "team": "Brooklyn Biotics",
    "teamColor": "#00c8ff",
    "position": "Manager",
    "jersey_number": 48,
    "gender": "male",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "bb_10",
    "name": "James Taylor",
    "team": "Brooklyn Biotics",
    "teamColor": "#00c8ff",
    "position": "Designated Hacker",
    "jersey_number": 58,
    "gender": "male",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "tt_1",
    "name": "Daiki Watanabe",
    "team": "Tokyo Tachyons",
    "teamColor": "#ff0088",
    "position": "Cyborg Pitcher",
    "jersey_number": 1,
    "gender": "male",
    "home_planet": "Kepler-186f",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "tt_2",
    "name": "Elon Chen",
    "team": "Tokyo Tachyons",
    "teamColor": "#ff0088",
    "position": "Bionic Shortstop",
    "jersey_number": 25,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "tt_3",
    "name": "Hina Nakamura",
    "team": "Tokyo Tachyons",
    "teamColor": "#ff0088",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 93,
    "gender": "female",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "tt_4",
    "name": "Hiroshi Tanaka",
    "team": "Tokyo Tachyons",
    "teamColor": "#ff0088",
    "position": "Laser Outfielder",
    "jersey_number": 16,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "tt_5",
    "name": "Akira Watanabe",
    "team": "Tokyo Tachyons",
    "teamColor": "#ff0088",
    "position": "Utility Android",
    "jersey_number": 77,
    "gender": "female",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "tt_6",
    "name": "Arjun Liu",
    "team": "Tokyo Tachyons",
    "teamColor": "#ff0088",
    "position": "Hover-Base Stealer",
    "jersey_number": 43,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "tt_7",
    "name": "Hiroshi Takahashi",
    "team": "Tokyo Tachyons",
    "teamColor": "#ff0088",
    "position": "Plasma Catcher",
    "jersey_number": 36,
    "gender": "male",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "tt_8",
    "name": "Kenji Nakamura",
    "team": "Tokyo Tachyons",
    "teamColor": "#ff0088",
    "position": "Relief Pitcher",
    "jersey_number": 46,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "tt_9",
    "name": "Echo Rider",
    "team": "Tokyo Tachyons",
    "teamColor": "#ff0088",
    "position": "Manager",
    "jersey_number": 68,
    "gender": "female",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "tt_10",
    "name": "Ren Moto",
    "team": "Tokyo Tachyons",
    "teamColor": "#ff0088",
    "position": "Designated Hacker",
    "jersey_number": 61,
    "gender": "male",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "nc_1",
    "name": "Diego Garcia",
    "team": "Neon City Sliders",
    "teamColor": "#00ff88",
    "position": "Cyborg Pitcher",
    "jersey_number": 93,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "nc_2",
    "name": "Cole Thomas",
    "team": "Neon City Sliders",
    "teamColor": "#00ff88",
    "position": "Bionic Shortstop",
    "jersey_number": 57,
    "gender": "male",
    "home_planet": "Kepler-186f",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "nc_3",
    "name": "Unit 52-F",
    "team": "Neon City Sliders",
    "teamColor": "#00ff88",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 69,
    "gender": "male",
    "home_planet": "Titan Station",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "nc_4",
    "name": "Laser Wire",
    "team": "Neon City Sliders",
    "teamColor": "#00ff88",
    "position": "Laser Outfielder",
    "jersey_number": 82,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "nc_5",
    "name": "Synth Code",
    "team": "Neon City Sliders",
    "teamColor": "#00ff88",
    "position": "Utility Android",
    "jersey_number": 39,
    "gender": "male",
    "home_planet": "Proxima Centauri b",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "nc_6",
    "name": "Pixel Maverick",
    "team": "Neon City Sliders",
    "teamColor": "#00ff88",
    "position": "Hover-Base Stealer",
    "jersey_number": 44,
    "gender": "female",
    "home_planet": "Titan Station",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "nc_7",
    "name": "Lyra Void",
    "team": "Neon City Sliders",
    "teamColor": "#00ff88",
    "position": "Plasma Catcher",
    "jersey_number": 31,
    "gender": "female",
    "home_planet": "Europa Sub-Oceanic",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "nc_8",
    "name": "Ananya Turing",
    "team": "Neon City Sliders",
    "teamColor": "#00ff88",
    "position": "Relief Pitcher",
    "jersey_number": 1,
    "gender": "female",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "nc_9",
    "name": "Elara",
    "team": "Neon City Sliders",
    "teamColor": "#00ff88",
    "position": "Manager",
    "jersey_number": 19,
    "gender": "female",
    "home_planet": "Europa Sub-Oceanic",
    "image": "/elara_manager.png"
  },
  {
    "id": "nc_10",
    "name": "Unit 90-S",
    "team": "Neon City Sliders",
    "teamColor": "#00ff88",
    "position": "Designated Hacker",
    "jersey_number": 78,
    "gender": "male",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "sv_1",
    "name": "Yuta Ito",
    "team": "Silicon Valley Sentinels",
    "teamColor": "#5555ff",
    "position": "Cyborg Pitcher",
    "jersey_number": 61,
    "gender": "male",
    "home_planet": "Kepler-186f",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "sv_2",
    "name": "Rahul Li",
    "team": "Silicon Valley Sentinels",
    "teamColor": "#5555ff",
    "position": "Bionic Shortstop",
    "jersey_number": 53,
    "gender": "male",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "sv_3",
    "name": "Echo Byte",
    "team": "Silicon Valley Sentinels",
    "teamColor": "#5555ff",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 75,
    "gender": "male",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "sv_4",
    "name": "Daiki Tanaka",
    "team": "Silicon Valley Sentinels",
    "teamColor": "#5555ff",
    "position": "Laser Outfielder",
    "jersey_number": 44,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "sv_5",
    "name": "Hunter Williams",
    "team": "Silicon Valley Sentinels",
    "teamColor": "#5555ff",
    "position": "Utility Android",
    "jersey_number": 9,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "sv_6",
    "name": "Isaiah Miller",
    "team": "Silicon Valley Sentinels",
    "teamColor": "#5555ff",
    "position": "Hover-Base Stealer",
    "jersey_number": 46,
    "gender": "male",
    "home_planet": "Proxima Centauri b",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "sv_7",
    "name": "Jada Wilson",
    "team": "Silicon Valley Sentinels",
    "teamColor": "#5555ff",
    "position": "Plasma Catcher",
    "jersey_number": 84,
    "gender": "female",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "sv_8",
    "name": "Kael Eclipse",
    "team": "Silicon Valley Sentinels",
    "teamColor": "#5555ff",
    "position": "Relief Pitcher",
    "jersey_number": 59,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "sv_9",
    "name": "Rahul Wu",
    "team": "Silicon Valley Sentinels",
    "teamColor": "#5555ff",
    "position": "Manager",
    "jersey_number": 62,
    "gender": "male",
    "home_planet": "Titan Station",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "sv_10",
    "name": "Wei Huang",
    "team": "Silicon Valley Sentinels",
    "teamColor": "#5555ff",
    "position": "Designated Hacker",
    "jersey_number": 90,
    "gender": "male",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "dt_1",
    "name": "Camila Johnson",
    "team": "Dallas Tex-Mechs",
    "teamColor": "#ff8800",
    "position": "Cyborg Pitcher",
    "jersey_number": 76,
    "gender": "female",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "dt_2",
    "name": "Luis Garcia",
    "team": "Dallas Tex-Mechs",
    "teamColor": "#ff8800",
    "position": "Bionic Shortstop",
    "jersey_number": 70,
    "gender": "male",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "dt_3",
    "name": "Mateo Sanchez",
    "team": "Dallas Tex-Mechs",
    "teamColor": "#ff8800",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 43,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "dt_4",
    "name": "Ananya Wu",
    "team": "Dallas Tex-Mechs",
    "teamColor": "#ff8800",
    "position": "Laser Outfielder",
    "jersey_number": 75,
    "gender": "female",
    "home_planet": "Titan Station",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "dt_5",
    "name": "Xen Void",
    "team": "Dallas Tex-Mechs",
    "teamColor": "#ff8800",
    "position": "Utility Android",
    "jersey_number": 19,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "dt_6",
    "name": "Chloe White",
    "team": "Dallas Tex-Mechs",
    "teamColor": "#ff8800",
    "position": "Hover-Base Stealer",
    "jersey_number": 38,
    "gender": "female",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "dt_7",
    "name": "Javier Brown",
    "team": "Dallas Tex-Mechs",
    "teamColor": "#ff8800",
    "position": "Plasma Catcher",
    "jersey_number": 20,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "dt_8",
    "name": "Luis Smith",
    "team": "Dallas Tex-Mechs",
    "teamColor": "#ff8800",
    "position": "Relief Pitcher",
    "jersey_number": 34,
    "gender": "male",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "dt_9",
    "name": "Carlos Lopez",
    "team": "Dallas Tex-Mechs",
    "teamColor": "#ff8800",
    "position": "Manager",
    "jersey_number": 63,
    "gender": "male",
    "home_planet": "Proxima Centauri b",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "dt_10",
    "name": "Julio Martinez",
    "team": "Dallas Tex-Mechs",
    "teamColor": "#ff8800",
    "position": "Designated Hacker",
    "jersey_number": 78,
    "gender": "male",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "oo_1",
    "name": "DeAndre Davis",
    "team": "Osaka Overclockers",
    "teamColor": "#ffcc00",
    "position": "Cyborg Pitcher",
    "jersey_number": 48,
    "gender": "male",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "oo_2",
    "name": "Diego Lopez",
    "team": "Osaka Overclockers",
    "teamColor": "#ffcc00",
    "position": "Bionic Shortstop",
    "jersey_number": 24,
    "gender": "male",
    "home_planet": "Titan Station",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "oo_3",
    "name": "Satoshi Tanaka",
    "team": "Osaka Overclockers",
    "teamColor": "#ffcc00",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 51,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "oo_4",
    "name": "Yuta Ito",
    "team": "Osaka Overclockers",
    "teamColor": "#ffcc00",
    "position": "Laser Outfielder",
    "jersey_number": 12,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "oo_5",
    "name": "Rafael Flores",
    "team": "Osaka Overclockers",
    "teamColor": "#ffcc00",
    "position": "Utility Android",
    "jersey_number": 70,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "oo_6",
    "name": "Harper Johnson",
    "team": "Osaka Overclockers",
    "teamColor": "#ffcc00",
    "position": "Hover-Base Stealer",
    "jersey_number": 15,
    "gender": "female",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "oo_7",
    "name": "Hiroshi Ito",
    "team": "Osaka Overclockers",
    "teamColor": "#ffcc00",
    "position": "Plasma Catcher",
    "jersey_number": 78,
    "gender": "male",
    "home_planet": "Kepler-186f",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "oo_8",
    "name": "Yuta Kobayashi",
    "team": "Osaka Overclockers",
    "teamColor": "#ffcc00",
    "position": "Relief Pitcher",
    "jersey_number": 96,
    "gender": "male",
    "home_planet": "Proxima Centauri b",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "oo_9",
    "name": "Xylar Quasar",
    "team": "Osaka Overclockers",
    "teamColor": "#ffcc00",
    "position": "Manager",
    "jersey_number": 77,
    "gender": "male",
    "home_planet": "Kepler-186f",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "oo_10",
    "name": "Takumi Kobayashi",
    "team": "Osaka Overclockers",
    "teamColor": "#ffcc00",
    "position": "Designated Hacker",
    "jersey_number": 47,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "kk_1",
    "name": "Takumi Yamamoto",
    "team": "Kyoto Kaiju",
    "teamColor": "#ff4444",
    "position": "Cyborg Pitcher",
    "jersey_number": 20,
    "gender": "male",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "kk_2",
    "name": "Akira Ryuko",
    "team": "Kyoto Kaiju",
    "teamColor": "#ff4444",
    "position": "Bionic Shortstop",
    "jersey_number": 30,
    "gender": "female",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "kk_3",
    "name": "Jaq Quasar",
    "team": "Kyoto Kaiju",
    "teamColor": "#ff4444",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 1,
    "gender": "male",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "kk_4",
    "name": "Jin Nakamura",
    "team": "Kyoto Kaiju",
    "teamColor": "#ff4444",
    "position": "Laser Outfielder",
    "jersey_number": 56,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "kk_5",
    "name": "Unit 69-T",
    "team": "Kyoto Kaiju",
    "teamColor": "#ff4444",
    "position": "Utility Android",
    "jersey_number": 69,
    "gender": "male",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "kk_6",
    "name": "Sho Watanabe",
    "team": "Kyoto Kaiju",
    "teamColor": "#ff4444",
    "position": "Hover-Base Stealer",
    "jersey_number": 21,
    "gender": "male",
    "home_planet": "Europa Sub-Oceanic",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "kk_7",
    "name": "Grox Void",
    "team": "Kyoto Kaiju",
    "teamColor": "#ff4444",
    "position": "Plasma Catcher",
    "jersey_number": 98,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "kk_8",
    "name": "Jin Sato",
    "team": "Kyoto Kaiju",
    "teamColor": "#ff4444",
    "position": "Relief Pitcher",
    "jersey_number": 39,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "kk_9",
    "name": "Isabella Torres",
    "team": "Kyoto Kaiju",
    "teamColor": "#ff4444",
    "position": "Manager",
    "jersey_number": 72,
    "gender": "female",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "kk_10",
    "name": "Miguel Flores",
    "team": "Kyoto Kaiju",
    "teamColor": "#ff4444",
    "position": "Designated Hacker",
    "jersey_number": 92,
    "gender": "male",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "rr_1",
    "name": "Drax Quasar",
    "team": "Roswell Rayguns",
    "teamColor": "#77ff00",
    "position": "Cyborg Pitcher",
    "jersey_number": 1,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "rr_2",
    "name": "Chloe Smith",
    "team": "Roswell Rayguns",
    "teamColor": "#77ff00",
    "position": "Bionic Shortstop",
    "jersey_number": 33,
    "gender": "female",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "rr_3",
    "name": "James Taylor",
    "team": "Roswell Rayguns",
    "teamColor": "#77ff00",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 69,
    "gender": "male",
    "home_planet": "Titan Station",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "rr_4",
    "name": "Cyber Code",
    "team": "Roswell Rayguns",
    "teamColor": "#77ff00",
    "position": "Laser Outfielder",
    "jersey_number": 73,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "rr_5",
    "name": "Zorblax X",
    "team": "Roswell Rayguns",
    "teamColor": "#77ff00",
    "position": "Utility Android",
    "jersey_number": 51,
    "gender": "male",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "rr_6",
    "name": "Chloe Jones",
    "team": "Roswell Rayguns",
    "teamColor": "#77ff00",
    "position": "Hover-Base Stealer",
    "jersey_number": 95,
    "gender": "female",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "rr_7",
    "name": "Alan Liu",
    "team": "Roswell Rayguns",
    "teamColor": "#77ff00",
    "position": "Plasma Catcher",
    "jersey_number": 44,
    "gender": "male",
    "home_planet": "Kepler-186f",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "rr_8",
    "name": "Vera X",
    "team": "Roswell Rayguns",
    "teamColor": "#77ff00",
    "position": "Relief Pitcher",
    "jersey_number": 72,
    "gender": "female",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "rr_9",
    "name": "Grox Alpha",
    "team": "Roswell Rayguns",
    "teamColor": "#77ff00",
    "position": "Manager",
    "jersey_number": 87,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "rr_10",
    "name": "Lucy Chen",
    "team": "Roswell Rayguns",
    "teamColor": "#77ff00",
    "position": "Designated Hacker",
    "jersey_number": 40,
    "gender": "female",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "aa_1",
    "name": "Elijah Brown",
    "team": "Atlanta Aerodynamics",
    "teamColor": "#aa00ff",
    "position": "Cyborg Pitcher",
    "jersey_number": 20,
    "gender": "male",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "aa_2",
    "name": "Elijah Anderson",
    "team": "Atlanta Aerodynamics",
    "teamColor": "#aa00ff",
    "position": "Bionic Shortstop",
    "jersey_number": 16,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "aa_3",
    "name": "Desmond Brown",
    "team": "Atlanta Aerodynamics",
    "teamColor": "#aa00ff",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 5,
    "gender": "male",
    "home_planet": "Europa Sub-Oceanic",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "aa_4",
    "name": "DeAndre Harris",
    "team": "Atlanta Aerodynamics",
    "teamColor": "#aa00ff",
    "position": "Laser Outfielder",
    "jersey_number": 39,
    "gender": "male",
    "home_planet": "Kepler-186f",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "aa_5",
    "name": "Unit 42-N",
    "team": "Atlanta Aerodynamics",
    "teamColor": "#aa00ff",
    "position": "Utility Android",
    "jersey_number": 44,
    "gender": "female",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "aa_6",
    "name": "Elijah Smith",
    "team": "Atlanta Aerodynamics",
    "teamColor": "#aa00ff",
    "position": "Hover-Base Stealer",
    "jersey_number": 27,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "aa_7",
    "name": "DeAndre White",
    "team": "Atlanta Aerodynamics",
    "teamColor": "#aa00ff",
    "position": "Plasma Catcher",
    "jersey_number": 35,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "aa_8",
    "name": "Chloe Jackson",
    "team": "Atlanta Aerodynamics",
    "teamColor": "#aa00ff",
    "position": "Relief Pitcher",
    "jersey_number": 75,
    "gender": "female",
    "home_planet": "Proxima Centauri b",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "aa_9",
    "name": "Sam Brown",
    "team": "Atlanta Aerodynamics",
    "teamColor": "#aa00ff",
    "position": "Manager",
    "jersey_number": 67,
    "gender": "female",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "aa_10",
    "name": "Ava Wilson",
    "team": "Atlanta Aerodynamics",
    "teamColor": "#aa00ff",
    "position": "Designated Hacker",
    "jersey_number": 61,
    "gender": "female",
    "home_planet": "Mars Colony Prime",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "mm_1",
    "name": "Julio Sanchez",
    "team": "Miami Motherboards",
    "teamColor": "#00ffff",
    "position": "Cyborg Pitcher",
    "jersey_number": 85,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "mm_2",
    "name": "Diego Torres",
    "team": "Miami Motherboards",
    "teamColor": "#00ffff",
    "position": "Bionic Shortstop",
    "jersey_number": 67,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "mm_3",
    "name": "Unit 61-C",
    "team": "Miami Motherboards",
    "teamColor": "#00ffff",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 7,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "mm_4",
    "name": "Unit 49-E",
    "team": "Miami Motherboards",
    "teamColor": "#00ffff",
    "position": "Laser Outfielder",
    "jersey_number": 11,
    "gender": "male",
    "home_planet": "Venus Cloud City",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "mm_5",
    "name": "Luis Torres",
    "team": "Miami Motherboards",
    "teamColor": "#00ffff",
    "position": "Utility Android",
    "jersey_number": 40,
    "gender": "male",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "mm_6",
    "name": "Mateo Hernandez",
    "team": "Miami Motherboards",
    "teamColor": "#00ffff",
    "position": "Hover-Base Stealer",
    "jersey_number": 39,
    "gender": "male",
    "home_planet": "Europa Sub-Oceanic",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "mm_7",
    "name": "Daiki Suzuki",
    "team": "Miami Motherboards",
    "teamColor": "#00ffff",
    "position": "Plasma Catcher",
    "jersey_number": 31,
    "gender": "male",
    "home_planet": "Europa Sub-Oceanic",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "mm_8",
    "name": "Miguel Hernandez",
    "team": "Miami Motherboards",
    "teamColor": "#00ffff",
    "position": "Relief Pitcher",
    "jersey_number": 34,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "mm_9",
    "name": "Rosa Gonzalez",
    "team": "Miami Motherboards",
    "teamColor": "#00ffff",
    "position": "Manager",
    "jersey_number": 76,
    "gender": "female",
    "home_planet": "Europa Sub-Oceanic",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "mm_10",
    "name": "Unit 84-G",
    "team": "Miami Motherboards",
    "teamColor": "#00ffff",
    "position": "Designated Hacker",
    "jersey_number": 68,
    "gender": "male",
    "home_planet": "Andromeda Outpost 9",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "sj_1",
    "name": "Rin Ito",
    "team": "San Juan Synthetics",
    "teamColor": "#ff00ff",
    "position": "Cyborg Pitcher",
    "jersey_number": 70,
    "gender": "female",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "sj_2",
    "name": "Elena Diaz",
    "team": "San Juan Synthetics",
    "teamColor": "#ff00ff",
    "position": "Bionic Shortstop",
    "jersey_number": 71,
    "gender": "female",
    "home_planet": "Kepler-186f",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "sj_3",
    "name": "Kael Omega",
    "team": "San Juan Synthetics",
    "teamColor": "#ff00ff",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 33,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "sj_4",
    "name": "Valentina Smith",
    "team": "San Juan Synthetics",
    "teamColor": "#ff00ff",
    "position": "Laser Outfielder",
    "jersey_number": 82,
    "gender": "female",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "sj_5",
    "name": "Miguel Gomez",
    "team": "San Juan Synthetics",
    "teamColor": "#ff00ff",
    "position": "Utility Android",
    "jersey_number": 65,
    "gender": "male",
    "home_planet": "Proxima Centauri b",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "sj_6",
    "name": "Rafael Flores",
    "team": "San Juan Synthetics",
    "teamColor": "#ff00ff",
    "position": "Hover-Base Stealer",
    "jersey_number": 17,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "sj_7",
    "name": "Hector Gonzalez",
    "team": "San Juan Synthetics",
    "teamColor": "#ff00ff",
    "position": "Plasma Catcher",
    "jersey_number": 94,
    "gender": "male",
    "home_planet": "Gliese 581g",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "sj_8",
    "name": "Javier Diaz",
    "team": "San Juan Synthetics",
    "teamColor": "#ff00ff",
    "position": "Relief Pitcher",
    "jersey_number": 0,
    "gender": "male",
    "home_planet": "Kepler-186f",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "sj_9",
    "name": "Camila Diaz",
    "team": "San Juan Synthetics",
    "teamColor": "#ff00ff",
    "position": "Manager",
    "jersey_number": 42,
    "gender": "female",
    "home_planet": "Titan Station",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "sj_10",
    "name": "Takumi Moto",
    "team": "San Juan Synthetics",
    "teamColor": "#ff00ff",
    "position": "Designated Hacker",
    "jersey_number": 5,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "hh_1",
    "name": "Diego Cruz",
    "team": "Havana Hover-Hounds",
    "teamColor": "#ccff00",
    "position": "Cyborg Pitcher",
    "jersey_number": 41,
    "gender": "male",
    "home_planet": "Titan Station",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "hh_2",
    "name": "Elena Sanchez",
    "team": "Havana Hover-Hounds",
    "teamColor": "#ccff00",
    "position": "Bionic Shortstop",
    "jersey_number": 6,
    "gender": "female",
    "home_planet": "Proxima Centauri b",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "hh_3",
    "name": "Julio Martinez",
    "team": "Havana Hover-Hounds",
    "teamColor": "#ccff00",
    "position": "Heavy Artillery (1B)",
    "jersey_number": 82,
    "gender": "male",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "hh_4",
    "name": "Vector Byte",
    "team": "Havana Hover-Hounds",
    "teamColor": "#ccff00",
    "position": "Laser Outfielder",
    "jersey_number": 53,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "hh_5",
    "name": "Daiki Kato",
    "team": "Havana Hover-Hounds",
    "teamColor": "#ccff00",
    "position": "Utility Android",
    "jersey_number": 27,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_card_tier1_hitter.png"
  },
  {
    "id": "hh_6",
    "name": "Leo Cruz",
    "team": "Havana Hover-Hounds",
    "teamColor": "#ccff00",
    "position": "Hover-Base Stealer",
    "jersey_number": 19,
    "gender": "male",
    "home_planet": "Titan Station",
    "image": "/cyborg_batter_series3.png"
  },
  {
    "id": "hh_7",
    "name": "Leo Rodriguez",
    "team": "Havana Hover-Hounds",
    "teamColor": "#ccff00",
    "position": "Plasma Catcher",
    "jersey_number": 29,
    "gender": "male",
    "home_planet": "Titan Station",
    "image": "/cyborg_catcher_series3.png"
  },
  {
    "id": "hh_8",
    "name": "Unit 63-V",
    "team": "Havana Hover-Hounds",
    "teamColor": "#ccff00",
    "position": "Relief Pitcher",
    "jersey_number": 17,
    "gender": "male",
    "home_planet": "Europa Sub-Oceanic",
    "image": "/cyborg_pitcher_series3.png"
  },
  {
    "id": "hh_9",
    "name": "Carmen Sanchez",
    "team": "Havana Hover-Hounds",
    "teamColor": "#ccff00",
    "position": "Manager",
    "jersey_number": 88,
    "gender": "female",
    "home_planet": "The Lunar Spire",
    "image": "/cyborg_card_tier2_holo_premium.png"
  },
  {
    "id": "hh_10",
    "name": "Yuta Yamada",
    "team": "Havana Hover-Hounds",
    "teamColor": "#ccff00",
    "position": "Designated Hacker",
    "jersey_number": 97,
    "gender": "male",
    "home_planet": "Earth (Sector 4)",
    "image": "/cyborg_batter_series3.png"
  }
];

export const TEAMS = [
  {
    "id": "bb",
    "name": "Brooklyn Biotics",
    "city": "Brooklyn",
    "color": "#00c8ff",
    "region": "east_us"
  },
  {
    "id": "tt",
    "name": "Tokyo Tachyons",
    "city": "Tokyo",
    "color": "#ff0088",
    "region": "japan"
  },
  {
    "id": "nc",
    "name": "Neon City Sliders",
    "city": "Neon City",
    "color": "#00ff88",
    "region": "cyber"
  },
  {
    "id": "sv",
    "name": "Silicon Valley Sentinels",
    "city": "Silicon Valley",
    "color": "#5555ff",
    "region": "tech"
  },
  {
    "id": "dt",
    "name": "Dallas Tex-Mechs",
    "city": "Dallas",
    "color": "#ff8800",
    "region": "south_us"
  },
  {
    "id": "oo",
    "name": "Osaka Overclockers",
    "city": "Osaka",
    "color": "#ffcc00",
    "region": "japan"
  },
  {
    "id": "kk",
    "name": "Kyoto Kaiju",
    "city": "Kyoto",
    "color": "#ff4444",
    "region": "japan"
  },
  {
    "id": "rr",
    "name": "Roswell Rayguns",
    "city": "Roswell",
    "color": "#77ff00",
    "region": "alien"
  },
  {
    "id": "aa",
    "name": "Atlanta Aerodynamics",
    "city": "Atlanta",
    "color": "#aa00ff",
    "region": "east_us"
  },
  {
    "id": "mm",
    "name": "Miami Motherboards",
    "city": "Miami",
    "color": "#00ffff",
    "region": "latino"
  },
  {
    "id": "sj",
    "name": "San Juan Synthetics",
    "city": "San Juan",
    "color": "#ff00ff",
    "region": "latino"
  },
  {
    "id": "hh",
    "name": "Havana Hover-Hounds",
    "city": "Havana",
    "color": "#ccff00",
    "region": "latino"
  }
];
